nbaspa_app/games/routes.py
"""Game information."""

from datetime import datetime

from flask import Blueprint, render_template
from flask import current_app as app

TODAY = datetime.today()

game_bp = Blueprint(
    "game_bp",
    __name__,
    template_folder=app.config["TEMPLATES_FOLDER"],
    static_folder=app.config["STATIC_FOLDER"],
    static_url_path=f"/games/{app.config['STATIC_FOLDER']}",
)


@game_bp.get(
    "/games", defaults={"day": TODAY.day, "month": TODAY.month, "year": TODAY.year}
)
@game_bp.get("/games/<int:day>/<int:month>/<int:year>")
def schedule(day: int, month: int, year: int):
    """The schedule page.

    Parameters
    ----------
    day : int
        The day of the games.
    month : int
        The month of the games.
    year : int
        The year of the games.
    """
    gamedate = datetime(year=year, month=month, day=day)
    return render_template(
        "schedule.html",
        title="Game Schedule",
        gamedate=gamedate.strftime("%A, %B %d, %Y"),
        day=day,
        month=month,
        year=year,
    )


@game_bp.get("/games/<int:day>/<int:month>/<int:year>/<gameid>")
def game(day: int, month: int, year: int, gameid: str):
    """The overall game summary page.

    Parameters
    ----------
    day : int
        The day of the games.
    month : int
        The month of the games.
    year : int
        The year of the games.
    gameid : str
        The game ID.
    """
    gamedate = datetime(year=year, month=month, day=day)
    return render_template(
        "game.html",
        year=gamedate.year,
        month=gamedate.month,
        day=gamedate.day,
        gameid=gameid,
    )

nbaspa_app/home/routes.py
"""Homepage information."""

from flask import Blueprint, render_template
from flask import current_app as app

from nbaspa.data.endpoints.parameters import CURRENT_SEASON

home_bp = Blueprint(
    "home_bp",
    __name__,
    template_folder=app.config["TEMPLATES_FOLDER"],
    static_folder=app.config["STATIC_FOLDER"],
    static_url_path=f"/home/{app.config['STATIC_FOLDER']}",
)


@home_bp.get("/")
@home_bp.get("/home")
@home_bp.get("/index")
def homepage():
    """Homepage."""
    return render_template("home.html", title="NBA SPA Homepage", season=CURRENT_SEASON)

nbaspa_app/league/routes.py
"""League pages."""

from flask import Blueprint, render_template, request
from flask import current_app as app

from nbaspa.data.endpoints.parameters import CURRENT_SEASON

league_bp = Blueprint(
    "league_bp",
    __name__,
    url_prefix="/league",
    template_folder=app.config["TEMPLATES_FOLDER"],
    static_folder=app.config["STATIC_FOLDER"],
    static_url_path=f"/league/{app.config['STATIC_FOLDER']}",
)


@league_bp.get("/mvp", defaults={"season": CURRENT_SEASON, "page": 1})
@league_bp.get("/mvp/<season>/<int:page>")
def mvp(season: str, page: int):
    """Produce an ordered list of players based on page."""
    return render_template(
        "mvp.html",
        title=f"{season} MVP Tracker",
        season=season,
        page=page,
        mode=request.args.get("mode", "survival-plus"),
        sortBy=request.args.get("sortBy", "mean"),
    )


@league_bp.get("/mip", defaults={"season": CURRENT_SEASON, "page": 1})
@league_bp.get("/mip/<season>/<int:page>")
def mip(season: str, page: int):
    """Produce an ordered list of players based on page."""
    return render_template(
        "mip.html",
        title=f"{season} MIP Tracker",
        season=season,
        page=page,
        mode=request.args.get("mode", "survival-plus"),
        sortBy=request.args.get("sortBy", "mean"),
    )


@league_bp.get("/roty", defaults={"season": CURRENT_SEASON, "page": 1})
@league_bp.get("/roty/<season>/<int:page>")
def roty(season: str, page: int):
    """Produce an ordered list of players based on page."""
    return render_template(
        "roty.html",
        title=f"{season} ROtY Tracker",
        season=season,
        page=page,
        mode=request.args.get("mode", "survival-plus"),
        sortBy=request.args.get("sortBy", "mean"),
    )


@league_bp.get("/season/<season>")
def season_home(season: str):
    """Get the season summary page.

    Parameters
    ----------
    season : str
        The season.
    """
    return render_template(
        "season_home.html",
        title=f"{season} Summary",
        season=season,
    )

nbaspa_app/teams/routes.py
"""Team information."""

from flask import Blueprint, render_template
from flask import current_app as app

teams_bp = Blueprint(
    "teams_bp",
    __name__,
    template_folder=app.config["TEMPLATES_FOLDER"],
    static_folder=app.config["STATIC_FOLDER"],
    static_url_path=f"/teams/{app.config['STATIC_FOLDER']}",
)


@teams_bp.get("/teams")
def teams_home():
    """Team homepage."""
    return render_template(
        "team_nav.html",
        title="Teams",
    )


@teams_bp.get("/teams/<int:teamid>")
def team_summary(teamid: int):
    """The team summary.

    Parameters
    ----------
    team_id : int
        The team identifier.
    """
    return render_template("teamsummary.html", teamid=teamid)


@teams_bp.get("/teams/<int:teamid>/<season>")
def team_season_summary(teamid: int, season: int):
    """The team season summary.

    Parameters
    ----------
    teamid : int
        The team identifier.
    season : str
        The season.
    """
    return render_template("teamseason.html", teamid=teamid, season=season)

nbaspa_app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ title }}</title>
        <!-- FONT -->
        <link href='//fonts.googleapis.com/css?family=Roboto:400,300,600' rel='stylesheet' type='text/css'>
        <!-- Font Awesome -->
        <script src="https://kit.fontawesome.com/aac33e0289.js" crossorigin="anonymous"></script>
        
        <!-- Mobile specific notes -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- CSS -->
        <link
        rel="stylesheet"
        href="{{ url_for(config['STATIC_FOLDER'], filename='dist/css/custom.css') }}"
        type='text/css'>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
        
        <!-- D3.js for data visualization -->
        <script src="https://d3js.org/d3.v7.min.js"></script>
        <!-- Load axios -->
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        {% block header %}{% endblock %}
    </head>
    <body class="has-background-light">
        <nav class="navbar is-dark" role="navigation" arial-label="main navigation">
            <div class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{{ url_for('home_bp.homepage') }}">Home</a>
                    <a class="navbar-item" href="{{ url_for('game_bp.schedule') }}">Games</a>
                    <a class="navbar-item" href="{{ url_for('teams_bp.teams_home') }}">Teams</a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">Seasons</a>
                        <div class="navbar-dropdown">
                            {% for row in config['SEASONS'] %}
                                <a class="navbar-item" href="{{ url_for('league_bp.season_home', season=row) }}">{{ row }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">Awards</a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{{ url_for('league_bp.mvp') }}">Most Valuable Player</a>
                            <a class="navbar-item" href="{{ url_for('league_bp.mip') }}">Most Improved Player</a>
                            <a class="navbar-item" href="{{ url_for('league_bp.roty') }}">Rookie of the Year</a>
                        </div>
                    </div>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{{ url_for('players_bp.player_directory') }}">Player Directory</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <br>
        <div class="container is-fluid">
            {% block content %}{% endblock %}
        </div>
        <br>
        <script>
            $SCRIPT_ROOT = {{ request.script_root|tojson }};
        </script>
    {% assets "shared_js" -%}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block jsScript %}{% endblock %}
    </body>
    <footer class="footer">
        <div class="content">
            <div class="columns">
                <div class="column is-half">
                    <p class="subtitle">Contact us</p>
                    <p><i class="fas fa-inbox"></i> akshay@breaktheboxscore.com</p>
                </div>
                <div class="column is-half">
                    <p class="subtitle">Quick links</p>
                    <p><a href="https://nbaspa.readthedocs.io/en/latest/_model/modelfit.html" target="_blank">Win probability model documentation</a></p>
                    <p><a href="https://nbaspa.readthedocs.io/en/latest/_spa/definition.html" target="_blank">Definition of player impact</a></p>
                    <p><a href="https://nbaspa.readthedocs.io/en/latest/notebooks/casestudy.html" target="_blank">Analysis of player impact ratings</a></p>
                </div>
            </div>
        </div>
    </footer>
</html>

nbaspa_app/templates/not_found.html
{% extends 'layout.html' %}

{% block content %}
    <h4 class="title">Sorry!</h4>
    <p>
        We can't find that data at the moment.
    </p>
{% endblock %}